services:
  - type: web
    name: dailyjob-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --workers 2 --threads 4 --worker-class gthread"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CELERY_EAGER
        value: "True"
      - key: BREVO_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "dailyjob2026@gmail.com"

  - type: cron
    name: dailyjob-cron
    runtime: python
    schedule: "0 * * * *"
    buildCommand: "./build.sh"
    startCommand: "python manage.py delete_expired_ads"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DATABASE_URL
        fromService:
          type: web
          name: dailyjob-backend
          envVarKey: DATABASE_URL
