# Generated by Django 6.1 on 2026-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(upload_to='transactions/receipts/'),
        ),
        migrations.DeleteModel(
            name='FlaggedKeyword',
        ),
    ]
