# Generated by Django 6.1 on 2026-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ad_image_url_ad_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterModelTable(
            name='ad',
            table='ads',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
