# Generated by Django 6.1 on 2026-08-16 16:22

from django.db import migrations


def fix_cascade(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER TABLE authtoken_token DROP CONSTRAINT IF EXISTS authtoken_token_user_id_35299eff_fk_core_user_id;
            ALTER TABLE authtoken_token DROP CONSTRAINT IF EXISTS authtoken_token_user_id_35299eff_fk_users_id;
            ALTER TABLE authtoken_token ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_id 
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
        """)


def reverse_fix_cascade(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER TABLE authtoken_token DROP CONSTRAINT IF EXISTS authtoken_token_user_id_35299eff_fk_users_id;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_options_alter_ad_status_alter_ad_table_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_cascade, reverse_fix_cascade),
    ]
