# Generated by Django 6.1 on 2026-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_authtoken_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ad_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
