# Generated by Django 6.1 on 2026-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
