# Generated by Django 6.1 on 2026-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_adcategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['method_name']},
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_method',
            field=models.CharField(choices=[('both', 'Both'), ('call', 'Call'), ('whatsapp', 'WhatsApp')], default='both', max_length=20),
        ),
    ]
