# Generated by Django 6.1 on 2026-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paymentmethod_options_ad_contact_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
