# Generated by Django 6.0.8 on 2026-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ad_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='وقت قبول الإعلان من الأدمن', null=True),
        ),
    ]
