# Generated by Django 6.0.8 on 2026-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_approved_at_to_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeCouponRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'welcome_coupon_records',
            },
        ),
    ]
