# Generated by Django 6.0.8 on 2026-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_real_estate_rentals_cars_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week')], default='1_day', max_length=20),
        ),
    ]
