# Generated by Django 6.0.8 on 2026-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ad_ad_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('cars', 'السيارات'), ('real_estate', 'العقار'), ('rent', 'الاجار'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='نوع الاعلان'),
        ),
    ]
