# Generated by Django 6.0.8 on 2026-09-04 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ad_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to='core.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_views',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('ad', 'user'), name='unique_ad_user_view')],
            },
        ),
    ]
