# Generated by Django 6.1 on 2026-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ad_category_alter_ad_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('cars', 'السيارات'), ('real_estate', 'العقار'), ('rent', 'إيجار'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='نوع الاعلان'),
        ),
    ]
