# Generated by Django 6.0.8 on 2026-09-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
