# Generated by Django 6.0.8 on 2026-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ad_deleted_at_ad_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_auto_approved',
            field=models.BooleanField(default=False, help_text='تمت الموافقة تلقائياً بعد انتهاء فترة المراجعة'),
        ),
    ]
