# Generated by Django 6.0.8 on 2026-09-19 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.', max_length=150, validators=[django.core.validators.RegexValidator(message='اسم المستخدم يمكن أن يحتوي على أحرف، أرقام، مسافات، أو الرموز (@ . + - _).', regex='^[\\w\\s.@+-]+$')], verbose_name='username'),
        ),
    ]
