# Generated by Django 6.0.8 on 2026-09-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ad_title',
            field=models.CharField(blank=True, default='', help_text='عنوان الإعلان المحفوظ للأرشيف', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.ad'),
        ),
    ]
